config = {
    'exp_name': '【0001】FULL DATASET TRAIN',
    'epoch': 30,
    'lr': 1.0,
    'mode': 'stroke',
    'batch': 64,
    'val_frequency': 3000,
    'test_only': False,
    'resume': './history/【0001】FULL DATASET TRAIN/best_model.pth',
    'train_dataset': '/kaggle/input/datasets/nancyjiwono/dbhandwriting/Trainmdb/Trainmdb',
    'test_dataset': '/kaggle/input/datasets/nancyjiwono/dbhandwriting/Testmdb/Testmdb',
    'weight_decay': False,
    'schedule_frequency': 5000,
    'image_size': 32,
    'alphabet': 3755,
}